### ISSUE TITLE
Request failed: Request failed with status code 400 and Request failed: Request failed with status code 500

### ISSUE THREAD

**Issue by deyman12** [TOR968/ClaytonBot#2]
is there an update on the server? `400` code is a client-side error which means the data might not match what the server needs, while `500` code clearly indicates a server error or maybe it has been changed? can you check and update it? because it could be that the `query_id` expired faster than usual.

![image](https://github.com/user-attachments/assets/4c1fa590-d003-4717-9907-2bab49fe40dd)
![Screenshot 2024-09-27 105631](https://github.com/user-attachments/assets/1b99e710-1ec7-4644-a46d-0bf1f01a45ac)

**Comment by TOR968** [comment]
with a 500 error, don't pay attention to it, they're doing something with their daily tasks,
![image](https://github.com/user-attachments/assets/63f42b70-87f0-44f3-b15b-5f2ba76dec02)
Looking for a solution with 400 errors

**Comment by TOR968** [comment]
for the 400 error, check if your accounts are subscribed to the official bot channel.
Done, please check if it works!
