### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by Fiqras** [TOR968/ClaytonBot#3]
![image](https://github.com/user-attachments/assets/193ca466-5a42-4c04-8e87-b42451749a05)

btw u hv group or channel tg ? maybe i can join

**Comment by TOR968** [comment]
Yes, they updated the addresses today, download the latest version.

**Comment by TOR968** [comment]
https://t.me/tor_dev

**Comment by Fiqras** [comment]
i'll waiting. ur best bro (y)
