### ISSUE TITLE
Failed 404

### ISSUE THREAD

**Issue by mainiken** [TOR968/ClaytonBot#4]
```
Processing account: Account
Logged in successfully
Daily reward not available
Token claim not available
Available game attempts: 3
Request failed: Request failed with status code 404
Error processing account Stanislav: Request failed with status code 404
```

I tried using both user= and query_id=
both methods give a 404 error
Help pls =)

**Comment by TOR968** [comment]
Because the game has been updated, a lot of things don't work there, when they fix everything I will make corrections. You can join the telegram at https://t.me/tor_dev and I will write there when I update
